fflch/dados

index.html
js/numeros.js

- implementado a biblioteca c3.js
- feito o gráfico de docentes e servidores

implementado a biblioteca c3.js

---

Queries/conta_alunoposdoutorado_filosofia.sql
Queries/conta_alunoposdoutorado_geografia.sql
Queries/conta_alunoposdoutorado_historia.sql
Queries/conta_alunoposdoutorado_letras.sql
Queries/conta_alunoposdoutorado_sociais.sql
app/Http/Controllers/AtivosPosDoutoradoPorCursoController.php
resources/views/ativosPosDoutoradoPorCurso.blade.php
resources/views/index.blade.php
routes/web.php

- As consultas trazem os alunos de pós-doutorado;
- Criado um novo controller para as consultas;

add novas consultas e controller

---

Queries/conta_micros_ativos.sql
Queries/conta_notes_ativos.sql

Corrige queries de micros e notes ativos

---

Queries/conta_beneficio_100_2019.sql
Queries/conta_beneficio_103_2019.sql
Queries/conta_beneficio_104_2019.sql
Queries/conta_beneficio_19_2019.sql
Queries/conta_beneficio_22_2019.sql
Queries/conta_beneficio_69_2019.sql
Queries/conta_beneficio_89_2019.sql
Queries/conta_beneficio_97_2019.sql
Queries/conta_beneficio_99_2019.sql
Queries/conta_beneficios_2014.sql
Queries/conta_beneficios_2015.sql
Queries/conta_beneficios_2016.sql
Queries/conta_beneficios_2017.sql
Queries/conta_beneficios_2018.sql
Queries/conta_beneficios_2019.sql
Queries/conta_beneficios_2020.sql
app/Http/Controllers/Beneficios2019PorProgramaController.php
app/Http/Controllers/BeneficiosConcedidosHistoricoController.php
resources/views/Benef2019Prog.blade.php
resources/views/ativosBeneficiosConHist.blade.php
resources/views/index.blade.php
routes/web.php

Série histórica de benefícios a partir de 2014 e benefícios por programa em 2019.

Série histórica de benefícios a partir de 2014 e Benefícios de 2019 por programa.

---

Queries/conta_convenios.sql
app/Http/Controllers/AtivosController.php
app/Http/Controllers/ConveniosAtivosController.php
resources/views/conveniosAtivos.blade.php
resources/views/index.blade.php
routes/web.php

iniciando as consultas sobre convênios

Consulta convênios ativos

---

Queries/conta_alunoceu_nao_nascidos_br.sql
Queries/conta_alunoceu_nascidos_br.sql
Queries/conta_alunoceu_nascidos_sem_info.sql
Queries/conta_alunogr_nao_nascidos_br.sql
Queries/conta_alunogr_nascidos_br.sql
Queries/conta_alunogr_nascidos_sem_info.sql
Queries/conta_alunopd_nao_nascidos_br.sql
Queries/conta_alunopd_nascidos_br.sql
Queries/conta_alunopd_nascidos_sem_info.sql
Queries/conta_alunopos_nao_nascidos_br.sql
Queries/conta_alunopos_nascidos_br.sql
Queries/conta_alunopos_nascidos_sem_info.sql
Queries/conta_docentes_nao_nascidos_br.sql
Queries/conta_docentes_nascidos_br.sql
Queries/conta_docentes_nascidos_sem_info.sql
app/Http/Controllers/AtivosCeuPaisNascimentoController.php
app/Http/Controllers/AtivosDocentesPaisNascimentoController.php
app/Http/Controllers/AtivosGradPaisNascimentoController.php
app/Http/Controllers/AtivosPDPaisNascimentoController.php
app/Http/Controllers/AtivosPosPaisNascimentoController.php
resources/views/ativosCeuPaisNasc.blade.php
resources/views/ativosDocentesPaisNasc.blade.php
resources/views/ativosGradPaisNasc.blade.php
resources/views/ativosPDPaisNasc.blade.php
resources/views/ativosPosPaisNasc.blade.php
resources/views/index.blade.php
routes/web.php

Lista ativos nascidos e não nascidos no Brasil da Cultura e Extensão Universitária, Graduação, Pós e Docentes.

Lista ativos de vários setores nascidos e não nascidos no Brasil

---

Queries/conta_alunospos_nivelpgm.sql
Queries/conta_orientadores_posgr.sql
app/Http/Controllers/AtivosPosNivelProgramaController.php
app/Http/Controllers/OrientadoresPosGRContoller.php
resources/views/ativosPosNivelPgm.blade.php
resources/views/index.blade.php
resources/views/orientadoresPosGR.blade.php
routes/web.php

novas consultas adicionadas e revisão de código

Novas consultas Pos-Graduação

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Http/Controllers/ProgramaController.php
resources/views/programas/docente.blade.php
resources/views/programas/show.blade.php

(Correção da conversão de array para json)

Corrigindo o replicadosync e adicionando outras produções na exibição

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Http/Controllers/Api/ProgramaController.php
app/Http/Controllers/ProgramaController.php
app/Models/Programa.php
resources/views/programas/docente.blade.php
resources/views/programas/show.blade.php
routes/api.php

Exição da apresentação de trabalhos técnicos.
API para a produção de docentes conforme o programa (programa::show).

Apresentações de trabalhos técnicos e API da produção de docentes

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Models/Programa.php
resources/views/programas/partials/autores.blade.php
resources/views/programas/pessoa.blade.php
resources/views/programas/show.blade.php

 Adição dos campos formação acadêmica e atuação profissional

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Models/Programa.php
resources/views/programas/pessoa.blade.php
resources/views/programas/show.blade.php

Exibição das seguintes categorias?
Organização de eventos
Curso de curta duração ministrado
Relatório de pesquisa
Matérial didático ou institucional
Outras Produções Técnicas

Exibição de novas produções técnicas na exportação de programas

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Http/Controllers/ProgramaController.php
resources/views/programas/pessoa.blade.php

Conflitos no ReplicadoSync e no Controller Programa

Resolvendo conflitos 

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Models/Programa.php
resources/views/programas/index.blade.php

Remoção dos var_dumps no replicadosync também

Transferindo a lógica do nome do curso e área do blade para a model 

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Http/Controllers/Api/ProgramaController.php
app/Http/Controllers/ProgramaController.php

Novo nome do método: listarAlunosAtivosPrograma

Renomeando método obterAtivosPorArea

---

app/Http/Controllers/Api/PessoaController.php
composer.lock
routes/api.php

para usar no site memorial fflch

Api Retornar Falecidos Por Periodo

---

Queries/listar_curso_ceu.sql
app/Http/Controllers/CEUController.php
app/Http/Controllers/RestritoController.php
resources/views/restrito.blade.php
resources/views/sobre.blade.php
routes/web.php

listar cursos a partir do departamento e ano

Consulta Cultura e Extensão EXCEL

---

Queries/listar_ex_alunos.sql
app/Http/Controllers/ExAlunosController.php
app/Http/Controllers/RestritoController.php
resources/views/restrito.blade.php
routes/web.php

Listagem já está funcionando. Depois será adicionada a lista de ex-alunos de pós-graduação e a filtragem por ano.

Listagem ex-alunos de graduação

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Http/Controllers/IniciacaoCientificaController.php
app/Http/Controllers/PesquisaController.php
app/Utils/Util.php
database/migrations/2021_05_25_154755_add_status_projeto_to_comissao_pesquisas_table.php
public/assets/css/programas.css
resources/views/pesquisa/index.blade.php
resources/views/pesquisa/iniciacao_cientifica.blade.php
resources/views/pesquisa/partials/return.blade.php
resources/views/pesquisa/partials/search.blade.php
resources/views/pesquisa/pesquisadores_colab.blade.php
resources/views/pesquisa/pesquisas_pos_doutorando.blade.php
resources/views/pesquisa/projetos_pesquisa.blade.php
routes/web.php

Para efetuar as atualizações precisa rodar o php artisan migrate, e o replicadosync. Alterei o replicadosync para que a parte de iniciação científica atualize primeiro. Além disso, precisa dar um update no replicado, foi modificado o controller Pessoa.

Filtro por data nas iniciações científicas

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Http/Controllers/ProgramaController.php
app/Models/Programa.php
resources/views/programas/partials/autores.blade.php
resources/views/programas/pessoa.blade.php

- O filtro de programas estava substituindo o id_lattes por codpes na URL, o que causava erro na pesquisa.
- As chaves dos orientandos e autores não estavam sendo verificadas
- Os integrantes da equipe de projeto de pesquisas não estavam aparecendo, pois estava com a chave errada.
- O padrão de busca foi definido para contar e listar TODAS as produções da pessoa.
- Ao sincronizar os docentes estava ocorrendo um erro de encoding, para corrigir foi preciso inserir a variável REPLICADO_SYBASE = 1.

Corrigindo bugs

---

app/Console/Commands/ReplicadoSyncCommand.php

Correção: O método syncJson estava salvando os registros e apagando alguns, pois faltava algumas condições para executar o delete().

Corrigindo bugs no replicadosync

---

resources/views/programas/pessoa.blade.php

O erro era no foreach(): argument must be of type array|object, bool given. Para corrigir, verifiquei se o valor que estava chegando era do tipo array ou objeto

Corrigindo log view Pessoas

---

app/Http/Controllers/Api/PessoaController.php
app/Http/Controllers/Api/ProgramaController.php
app/Models/Pessoa.php

Api Monitores - Arrumando formato das datas e retirando barras ao contrário

---

app/Models/Defesa.php
app/Providers/AppServiceProvider.php
resources/views/defesas/index.blade.php

Para paginar uma Collection foi preciso alterar o método boot do arquivo AppServiceProvider.php
https://gist.github.com/simonhamp/549e8821946e2c40a617c85d2cf5af5e

Paginador na página defesas

---

app/Http/Controllers/TrancamentosCursoSemestralController.php
resources/views/index.blade.php
resources/views/trancamentosCursoPorSemestre.blade.php
routes/web.php

Parametrizando o período de anos em TrancamentoCursoPorSemestre

---

app/Console/Commands/ReplicadoSyncCommand.php
app/Http/Controllers/Api/DefesaController.php
app/Http/Controllers/DefesaController.php
app/Models/Defesa.php
app/Providers/AppServiceProvider.php
database/migrations/2021_09_29_210659_create_defesas_table.php
resources/views/defesas/index.blade.php

Lembrete: é preciso rodar o php artisan migrate e o replicadosync também, uma vez que as defesas serão aramazenadas no banco local agora.

Armazenando as defesas no banco local e implementação da paginação

---

resources/views/index.blade.php
routes/web.php

Como tem ingressantes da pós e da graduação agora, eu alterei a rota ingressantesGeneroCurso para IngressantesGradGeneroCurso em contrposição à  IngressantesPosGrdCursoGenero

Mudando a rota IngressantesGeneroCuro para IngressantesGradGeneroCurs

---

app/Console/Commands/ReplicadoDailySyncCommand.php
app/Console/Commands/ReplicadoLattesSyncCommand.php
app/Console/Commands/ReplicadoWeeklySyncCommand.php
app/Console/Kernel.php
app/Utils/ReplicadoTemp.php
database/migrations/2022_04_18_160844_add_sexo_cor_to_comissao_pesquisas_table.php
database/migrations/2022_04_19_131549_add_data_ini_fim_bolsa_to_comissao_pesquisas_table.php

A tabela Lattes agora só relaciona o json que contém os dados do lattes e o codpes

Separando as infos do lattes em outro comando

---

app/Http/Controllers/Api/ProgramaController.php
app/Http/Controllers/IngressantesPosGrGeneroProgramaController.php
app/Http/Controllers/ProgramaController.php
app/Models/Programa.php
config/database.php
resources/views/index.blade.php
resources/views/programas/index.blade.php
resources/views/programas/show.blade.php

Nas páginas que listam os docentes/discentes/egressos tem a opção de exportar em excel. Ex. http://127.0.0.1:8000/programas/docentes/8131
Aceitar primeiro a PR do repelicadosyn https://github.com/fflch/dados/pull/219

Adpatando as buscas de dados conforme o novo comando replicadolattessync  e exportando em excel a tabela de produção academica

---

app/Models/Programa.php

Fix  #223 
Corrigindo o erro do log:
Undefined variable: departamentos {"exception":"[object] (ErrorException(code: 0): Undefined variable: departamentos at /var/www/dados.fflch.usp.br/app/Models/Programa.php:25)
/var/www/dados.fflch.usp.br/app/Http/Controllers/ProgramaController.php(26): App\\Models\\Programa::index()
declarando a variavel $departamentos com um valor padrao.

Fix: Tratar os erros quando o banco de dados está zerado/sincronizando.

---

app/Console/Commands/ReplicadoLattesSyncCommand.php
app/Http/Controllers/Api/ProgramaController.php
app/Http/Controllers/ProgramaController.php
app/Models/Programa.php
database/migrations/2022_06_30_122537_drop_columns_programas_lattes_table.php
database/migrations/2022_06_30_126306_add_id_lattes_to_lattes.php

Substituindo o codpes por id_lattes em /api/programas

---

app/Console/Commands/ReplicadoLattesSyncCommand.php
app/Http/Controllers/Api/ProgramaController.php
app/Http/Controllers/IngressantesPosGrGeneroProgramaController.php
app/Http/Controllers/ProgramaController.php
app/Models/Programa.php

Incluindo os docentes aposentados na parte de programa (replicadolattessync);
adicionando o parâmetro do excel do método listarEgressos (programacontroller);
corrigindo a chave do array de programas (IngressantesPosGrGeneroProgramaController);
buscando os dados pelo idLattes em vez do codpes (programa).

Corrigindo erros

---

resources/views/layouts/navbars/sidebar.blade.php

- Correção das URL's no sidebar menu

Corrigindo URL's quebradas

---

resources/views/contato.blade.php

Atualizei a página para ter o mesmo layout do site, com as informações corretas dos estagiários, contato e  localização (no rodapé).

Atualização da página 'contato' e inserção do rodapé

---

resources/views/paginaInicial.blade.php

Retirou-se a seção departamentos já que não possui funcionalidades.

Retirada da seção Departamentos

---

Queries/listar_intercambistas_recebidos.sql
app/Http/Controllers/Restrito/IntercambistasController.php
composer.json
composer.lock
resources/views/restrito.blade.php
routes/web.php
storage/debugbar/.gitignore

1° Implementação de query: intercambistas recebidos, com descrição.

1° Implementação de query: intercambistas recebidos, com descrição

---

app/Http/Controllers/DisciplinaController.php
app/Models/Disciplina.php
app/Utils/ReplicadoTemp.php
app/Utils/Util.php
composer.lock
public/robots.txt
resources/views/disciplinas/concatenate.blade.php
resources/views/disciplinas/turma.blade.php
resources/views/disciplinas/turmas.blade.php
resources/views/index.blade.php
routes/web.php

Implementação da seção de turmas e disciplinas. Alterações aprovadas pelo EAIP.

Adição das funcionalidades de turmas e disciplinas
